dataset: Faces
split: Adush
dataset_source: Faces
split_source: PavelSemenov
type: train

workers: 4
crop_size: 256
batch_size: 64
shuffle: True
PDB: False
GAN: True

cuda: True
gpu_id: 0

loss_type: smoothL1
loss_gp_lambda: 0.01
loss_edge_lambda: 1000.0
optimizer: Adam
momentum: 0.0
weight_decay: 0
lr: 1e-3

flame_dataset_mean_shape: True
flame_random_params: True

resume_epoch: 20
save_logs: True
save_img: True

eval_epoch_estimator: 1085

