dataset: Faces
split: Adush
type: train

eval_epoch_estimator: 1085


workers: 0
batch_size: 4
dataset_indexes:
  - 0
  - 1
  - 2
  - 3

RGB: True
gp_loss: True
cp_loss: True

max_epoch: 10000
save_logs: True